sudo: required

services:
  - docker

env:
  - IMAGE=crime-scene-tools

script:
  - docker build -t $IMAGE .
  # Make .git/ available for log
  # but use the embedded working dir to get access to downloaded scripts.
  - docker run -v $(cd bin && git rev-parse --git-dir):/usr/src/cst/.git $IMAGE make test
